
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Project'
export type * from './models/Service'
export type * from './models/BlogPost'
export type * from './models/ContactMessage'
export type * from './models/SiteSetting'
export type * from './models/Testimonial'
export type * from './models/Technology'
export type * from './models/StudentOrder'
export type * from './models/StudentAward'
export type * from './models/StudentCertificate'
export type * from './models/StudentResearch'
export type * from './models/BusinessOrder'
export type * from './models/HeroContent'
export type * from './models/SEOSettings'
export type * from './commonInputTypes'