
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Project: 'Project',
  Service: 'Service',
  BlogPost: 'BlogPost',
  ContactMessage: 'ContactMessage',
  SiteSetting: 'SiteSetting',
  Testimonial: 'Testimonial',
  Technology: 'Technology',
  StudentOrder: 'StudentOrder',
  StudentAward: 'StudentAward',
  StudentCertificate: 'StudentCertificate',
  StudentResearch: 'StudentResearch',
  BusinessOrder: 'BusinessOrder',
  HeroContent: 'HeroContent',
  SEOSettings: 'SEOSettings'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "project" | "service" | "blogPost" | "contactMessage" | "siteSetting" | "testimonial" | "technology" | "studentOrder" | "studentAward" | "studentCertificate" | "studentResearch" | "businessOrder" | "heroContent" | "sEOSettings"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Project: {
      payload: Prisma.$ProjectPayload<ExtArgs>
      fields: Prisma.ProjectFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProjectFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProjectFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        findFirst: {
          args: Prisma.ProjectFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProjectFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        findMany: {
          args: Prisma.ProjectFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>[]
        }
        create: {
          args: Prisma.ProjectCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        createMany: {
          args: Prisma.ProjectCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProjectCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>[]
        }
        delete: {
          args: Prisma.ProjectDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        update: {
          args: Prisma.ProjectUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        deleteMany: {
          args: Prisma.ProjectDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProjectUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProjectUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>[]
        }
        upsert: {
          args: Prisma.ProjectUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        aggregate: {
          args: Prisma.ProjectAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProject>
        }
        groupBy: {
          args: Prisma.ProjectGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProjectGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProjectCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProjectCountAggregateOutputType> | number
        }
      }
    }
    Service: {
      payload: Prisma.$ServicePayload<ExtArgs>
      fields: Prisma.ServiceFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ServiceFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ServiceFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        findFirst: {
          args: Prisma.ServiceFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ServiceFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        findMany: {
          args: Prisma.ServiceFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>[]
        }
        create: {
          args: Prisma.ServiceCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        createMany: {
          args: Prisma.ServiceCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ServiceCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>[]
        }
        delete: {
          args: Prisma.ServiceDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        update: {
          args: Prisma.ServiceUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        deleteMany: {
          args: Prisma.ServiceDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ServiceUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ServiceUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>[]
        }
        upsert: {
          args: Prisma.ServiceUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicePayload>
        }
        aggregate: {
          args: Prisma.ServiceAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateService>
        }
        groupBy: {
          args: Prisma.ServiceGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ServiceGroupByOutputType>[]
        }
        count: {
          args: Prisma.ServiceCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ServiceCountAggregateOutputType> | number
        }
      }
    }
    BlogPost: {
      payload: Prisma.$BlogPostPayload<ExtArgs>
      fields: Prisma.BlogPostFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BlogPostFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BlogPostFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload>
        }
        findFirst: {
          args: Prisma.BlogPostFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BlogPostFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload>
        }
        findMany: {
          args: Prisma.BlogPostFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload>[]
        }
        create: {
          args: Prisma.BlogPostCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload>
        }
        createMany: {
          args: Prisma.BlogPostCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BlogPostCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload>[]
        }
        delete: {
          args: Prisma.BlogPostDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload>
        }
        update: {
          args: Prisma.BlogPostUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload>
        }
        deleteMany: {
          args: Prisma.BlogPostDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BlogPostUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BlogPostUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload>[]
        }
        upsert: {
          args: Prisma.BlogPostUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BlogPostPayload>
        }
        aggregate: {
          args: Prisma.BlogPostAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBlogPost>
        }
        groupBy: {
          args: Prisma.BlogPostGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BlogPostGroupByOutputType>[]
        }
        count: {
          args: Prisma.BlogPostCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BlogPostCountAggregateOutputType> | number
        }
      }
    }
    ContactMessage: {
      payload: Prisma.$ContactMessagePayload<ExtArgs>
      fields: Prisma.ContactMessageFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ContactMessageFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ContactMessageFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload>
        }
        findFirst: {
          args: Prisma.ContactMessageFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ContactMessageFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload>
        }
        findMany: {
          args: Prisma.ContactMessageFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload>[]
        }
        create: {
          args: Prisma.ContactMessageCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload>
        }
        createMany: {
          args: Prisma.ContactMessageCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ContactMessageCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload>[]
        }
        delete: {
          args: Prisma.ContactMessageDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload>
        }
        update: {
          args: Prisma.ContactMessageUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload>
        }
        deleteMany: {
          args: Prisma.ContactMessageDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ContactMessageUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ContactMessageUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload>[]
        }
        upsert: {
          args: Prisma.ContactMessageUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContactMessagePayload>
        }
        aggregate: {
          args: Prisma.ContactMessageAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateContactMessage>
        }
        groupBy: {
          args: Prisma.ContactMessageGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContactMessageGroupByOutputType>[]
        }
        count: {
          args: Prisma.ContactMessageCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContactMessageCountAggregateOutputType> | number
        }
      }
    }
    SiteSetting: {
      payload: Prisma.$SiteSettingPayload<ExtArgs>
      fields: Prisma.SiteSettingFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SiteSettingFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SiteSettingFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload>
        }
        findFirst: {
          args: Prisma.SiteSettingFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SiteSettingFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload>
        }
        findMany: {
          args: Prisma.SiteSettingFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload>[]
        }
        create: {
          args: Prisma.SiteSettingCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload>
        }
        createMany: {
          args: Prisma.SiteSettingCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SiteSettingCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload>[]
        }
        delete: {
          args: Prisma.SiteSettingDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload>
        }
        update: {
          args: Prisma.SiteSettingUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload>
        }
        deleteMany: {
          args: Prisma.SiteSettingDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SiteSettingUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SiteSettingUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload>[]
        }
        upsert: {
          args: Prisma.SiteSettingUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SiteSettingPayload>
        }
        aggregate: {
          args: Prisma.SiteSettingAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSiteSetting>
        }
        groupBy: {
          args: Prisma.SiteSettingGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SiteSettingGroupByOutputType>[]
        }
        count: {
          args: Prisma.SiteSettingCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SiteSettingCountAggregateOutputType> | number
        }
      }
    }
    Testimonial: {
      payload: Prisma.$TestimonialPayload<ExtArgs>
      fields: Prisma.TestimonialFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TestimonialFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TestimonialFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload>
        }
        findFirst: {
          args: Prisma.TestimonialFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TestimonialFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload>
        }
        findMany: {
          args: Prisma.TestimonialFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload>[]
        }
        create: {
          args: Prisma.TestimonialCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload>
        }
        createMany: {
          args: Prisma.TestimonialCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TestimonialCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload>[]
        }
        delete: {
          args: Prisma.TestimonialDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload>
        }
        update: {
          args: Prisma.TestimonialUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload>
        }
        deleteMany: {
          args: Prisma.TestimonialDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TestimonialUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TestimonialUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload>[]
        }
        upsert: {
          args: Prisma.TestimonialUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TestimonialPayload>
        }
        aggregate: {
          args: Prisma.TestimonialAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTestimonial>
        }
        groupBy: {
          args: Prisma.TestimonialGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TestimonialGroupByOutputType>[]
        }
        count: {
          args: Prisma.TestimonialCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TestimonialCountAggregateOutputType> | number
        }
      }
    }
    Technology: {
      payload: Prisma.$TechnologyPayload<ExtArgs>
      fields: Prisma.TechnologyFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TechnologyFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TechnologyFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload>
        }
        findFirst: {
          args: Prisma.TechnologyFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TechnologyFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload>
        }
        findMany: {
          args: Prisma.TechnologyFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload>[]
        }
        create: {
          args: Prisma.TechnologyCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload>
        }
        createMany: {
          args: Prisma.TechnologyCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TechnologyCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload>[]
        }
        delete: {
          args: Prisma.TechnologyDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload>
        }
        update: {
          args: Prisma.TechnologyUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload>
        }
        deleteMany: {
          args: Prisma.TechnologyDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TechnologyUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TechnologyUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload>[]
        }
        upsert: {
          args: Prisma.TechnologyUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TechnologyPayload>
        }
        aggregate: {
          args: Prisma.TechnologyAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTechnology>
        }
        groupBy: {
          args: Prisma.TechnologyGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TechnologyGroupByOutputType>[]
        }
        count: {
          args: Prisma.TechnologyCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TechnologyCountAggregateOutputType> | number
        }
      }
    }
    StudentOrder: {
      payload: Prisma.$StudentOrderPayload<ExtArgs>
      fields: Prisma.StudentOrderFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StudentOrderFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StudentOrderFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload>
        }
        findFirst: {
          args: Prisma.StudentOrderFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StudentOrderFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload>
        }
        findMany: {
          args: Prisma.StudentOrderFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload>[]
        }
        create: {
          args: Prisma.StudentOrderCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload>
        }
        createMany: {
          args: Prisma.StudentOrderCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StudentOrderCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload>[]
        }
        delete: {
          args: Prisma.StudentOrderDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload>
        }
        update: {
          args: Prisma.StudentOrderUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload>
        }
        deleteMany: {
          args: Prisma.StudentOrderDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StudentOrderUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StudentOrderUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload>[]
        }
        upsert: {
          args: Prisma.StudentOrderUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentOrderPayload>
        }
        aggregate: {
          args: Prisma.StudentOrderAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStudentOrder>
        }
        groupBy: {
          args: Prisma.StudentOrderGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudentOrderGroupByOutputType>[]
        }
        count: {
          args: Prisma.StudentOrderCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudentOrderCountAggregateOutputType> | number
        }
      }
    }
    StudentAward: {
      payload: Prisma.$StudentAwardPayload<ExtArgs>
      fields: Prisma.StudentAwardFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StudentAwardFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StudentAwardFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload>
        }
        findFirst: {
          args: Prisma.StudentAwardFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StudentAwardFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload>
        }
        findMany: {
          args: Prisma.StudentAwardFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload>[]
        }
        create: {
          args: Prisma.StudentAwardCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload>
        }
        createMany: {
          args: Prisma.StudentAwardCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StudentAwardCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload>[]
        }
        delete: {
          args: Prisma.StudentAwardDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload>
        }
        update: {
          args: Prisma.StudentAwardUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload>
        }
        deleteMany: {
          args: Prisma.StudentAwardDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StudentAwardUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StudentAwardUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload>[]
        }
        upsert: {
          args: Prisma.StudentAwardUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentAwardPayload>
        }
        aggregate: {
          args: Prisma.StudentAwardAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStudentAward>
        }
        groupBy: {
          args: Prisma.StudentAwardGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudentAwardGroupByOutputType>[]
        }
        count: {
          args: Prisma.StudentAwardCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudentAwardCountAggregateOutputType> | number
        }
      }
    }
    StudentCertificate: {
      payload: Prisma.$StudentCertificatePayload<ExtArgs>
      fields: Prisma.StudentCertificateFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StudentCertificateFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StudentCertificateFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload>
        }
        findFirst: {
          args: Prisma.StudentCertificateFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StudentCertificateFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload>
        }
        findMany: {
          args: Prisma.StudentCertificateFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload>[]
        }
        create: {
          args: Prisma.StudentCertificateCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload>
        }
        createMany: {
          args: Prisma.StudentCertificateCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StudentCertificateCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload>[]
        }
        delete: {
          args: Prisma.StudentCertificateDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload>
        }
        update: {
          args: Prisma.StudentCertificateUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload>
        }
        deleteMany: {
          args: Prisma.StudentCertificateDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StudentCertificateUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StudentCertificateUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload>[]
        }
        upsert: {
          args: Prisma.StudentCertificateUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentCertificatePayload>
        }
        aggregate: {
          args: Prisma.StudentCertificateAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStudentCertificate>
        }
        groupBy: {
          args: Prisma.StudentCertificateGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudentCertificateGroupByOutputType>[]
        }
        count: {
          args: Prisma.StudentCertificateCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudentCertificateCountAggregateOutputType> | number
        }
      }
    }
    StudentResearch: {
      payload: Prisma.$StudentResearchPayload<ExtArgs>
      fields: Prisma.StudentResearchFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StudentResearchFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StudentResearchFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload>
        }
        findFirst: {
          args: Prisma.StudentResearchFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StudentResearchFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload>
        }
        findMany: {
          args: Prisma.StudentResearchFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload>[]
        }
        create: {
          args: Prisma.StudentResearchCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload>
        }
        createMany: {
          args: Prisma.StudentResearchCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StudentResearchCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload>[]
        }
        delete: {
          args: Prisma.StudentResearchDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload>
        }
        update: {
          args: Prisma.StudentResearchUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload>
        }
        deleteMany: {
          args: Prisma.StudentResearchDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StudentResearchUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StudentResearchUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload>[]
        }
        upsert: {
          args: Prisma.StudentResearchUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StudentResearchPayload>
        }
        aggregate: {
          args: Prisma.StudentResearchAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStudentResearch>
        }
        groupBy: {
          args: Prisma.StudentResearchGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudentResearchGroupByOutputType>[]
        }
        count: {
          args: Prisma.StudentResearchCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StudentResearchCountAggregateOutputType> | number
        }
      }
    }
    BusinessOrder: {
      payload: Prisma.$BusinessOrderPayload<ExtArgs>
      fields: Prisma.BusinessOrderFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BusinessOrderFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BusinessOrderFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload>
        }
        findFirst: {
          args: Prisma.BusinessOrderFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BusinessOrderFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload>
        }
        findMany: {
          args: Prisma.BusinessOrderFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload>[]
        }
        create: {
          args: Prisma.BusinessOrderCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload>
        }
        createMany: {
          args: Prisma.BusinessOrderCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BusinessOrderCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload>[]
        }
        delete: {
          args: Prisma.BusinessOrderDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload>
        }
        update: {
          args: Prisma.BusinessOrderUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload>
        }
        deleteMany: {
          args: Prisma.BusinessOrderDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BusinessOrderUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BusinessOrderUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload>[]
        }
        upsert: {
          args: Prisma.BusinessOrderUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BusinessOrderPayload>
        }
        aggregate: {
          args: Prisma.BusinessOrderAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBusinessOrder>
        }
        groupBy: {
          args: Prisma.BusinessOrderGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BusinessOrderGroupByOutputType>[]
        }
        count: {
          args: Prisma.BusinessOrderCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BusinessOrderCountAggregateOutputType> | number
        }
      }
    }
    HeroContent: {
      payload: Prisma.$HeroContentPayload<ExtArgs>
      fields: Prisma.HeroContentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.HeroContentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.HeroContentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload>
        }
        findFirst: {
          args: Prisma.HeroContentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.HeroContentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload>
        }
        findMany: {
          args: Prisma.HeroContentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload>[]
        }
        create: {
          args: Prisma.HeroContentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload>
        }
        createMany: {
          args: Prisma.HeroContentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.HeroContentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload>[]
        }
        delete: {
          args: Prisma.HeroContentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload>
        }
        update: {
          args: Prisma.HeroContentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload>
        }
        deleteMany: {
          args: Prisma.HeroContentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.HeroContentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.HeroContentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload>[]
        }
        upsert: {
          args: Prisma.HeroContentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$HeroContentPayload>
        }
        aggregate: {
          args: Prisma.HeroContentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateHeroContent>
        }
        groupBy: {
          args: Prisma.HeroContentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HeroContentGroupByOutputType>[]
        }
        count: {
          args: Prisma.HeroContentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.HeroContentCountAggregateOutputType> | number
        }
      }
    }
    SEOSettings: {
      payload: Prisma.$SEOSettingsPayload<ExtArgs>
      fields: Prisma.SEOSettingsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SEOSettingsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SEOSettingsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload>
        }
        findFirst: {
          args: Prisma.SEOSettingsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SEOSettingsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload>
        }
        findMany: {
          args: Prisma.SEOSettingsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload>[]
        }
        create: {
          args: Prisma.SEOSettingsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload>
        }
        createMany: {
          args: Prisma.SEOSettingsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SEOSettingsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload>[]
        }
        delete: {
          args: Prisma.SEOSettingsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload>
        }
        update: {
          args: Prisma.SEOSettingsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload>
        }
        deleteMany: {
          args: Prisma.SEOSettingsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SEOSettingsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SEOSettingsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload>[]
        }
        upsert: {
          args: Prisma.SEOSettingsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SEOSettingsPayload>
        }
        aggregate: {
          args: Prisma.SEOSettingsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSEOSettings>
        }
        groupBy: {
          args: Prisma.SEOSettingsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SEOSettingsGroupByOutputType>[]
        }
        count: {
          args: Prisma.SEOSettingsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SEOSettingsCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  image: 'image',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  image: 'image',
  tags: 'tags',
  demoUrl: 'demoUrl',
  githubUrl: 'githubUrl',
  featured: 'featured',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const ServiceScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  price: 'price',
  currency: 'currency',
  period: 'period',
  features: 'features',
  popular: 'popular',
  gradient: 'gradient',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ServiceScalarFieldEnum = (typeof ServiceScalarFieldEnum)[keyof typeof ServiceScalarFieldEnum]


export const BlogPostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  excerpt: 'excerpt',
  content: 'content',
  image: 'image',
  author: 'author',
  tags: 'tags',
  published: 'published',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BlogPostScalarFieldEnum = (typeof BlogPostScalarFieldEnum)[keyof typeof BlogPostScalarFieldEnum]


export const ContactMessageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  subject: 'subject',
  message: 'message',
  read: 'read',
  createdAt: 'createdAt'
} as const

export type ContactMessageScalarFieldEnum = (typeof ContactMessageScalarFieldEnum)[keyof typeof ContactMessageScalarFieldEnum]


export const SiteSettingScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value'
} as const

export type SiteSettingScalarFieldEnum = (typeof SiteSettingScalarFieldEnum)[keyof typeof SiteSettingScalarFieldEnum]


export const TestimonialScalarFieldEnum = {
  id: 'id',
  name: 'name',
  role: 'role',
  company: 'company',
  content: 'content',
  avatar: 'avatar',
  rating: 'rating',
  createdAt: 'createdAt'
} as const

export type TestimonialScalarFieldEnum = (typeof TestimonialScalarFieldEnum)[keyof typeof TestimonialScalarFieldEnum]


export const TechnologyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  icon: 'icon',
  category: 'category',
  order: 'order',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TechnologyScalarFieldEnum = (typeof TechnologyScalarFieldEnum)[keyof typeof TechnologyScalarFieldEnum]


export const StudentOrderScalarFieldEnum = {
  id: 'id',
  orderCode: 'orderCode',
  fullName: 'fullName',
  profileImage: 'profileImage',
  address: 'address',
  email: 'email',
  phone: 'phone',
  githubUrl: 'githubUrl',
  linkedinUrl: 'linkedinUrl',
  degree: 'degree',
  institution: 'institution',
  educationStartDate: 'educationStartDate',
  educationEndDate: 'educationEndDate',
  company: 'company',
  position: 'position',
  duration: 'duration',
  experienceDescription: 'experienceDescription',
  skills: 'skills',
  activities: 'activities',
  additionalNotes: 'additionalNotes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StudentOrderScalarFieldEnum = (typeof StudentOrderScalarFieldEnum)[keyof typeof StudentOrderScalarFieldEnum]


export const StudentAwardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  date: 'date',
  image: 'image',
  orderId: 'orderId',
  createdAt: 'createdAt'
} as const

export type StudentAwardScalarFieldEnum = (typeof StudentAwardScalarFieldEnum)[keyof typeof StudentAwardScalarFieldEnum]


export const StudentCertificateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  date: 'date',
  file: 'file',
  orderId: 'orderId',
  createdAt: 'createdAt'
} as const

export type StudentCertificateScalarFieldEnum = (typeof StudentCertificateScalarFieldEnum)[keyof typeof StudentCertificateScalarFieldEnum]


export const StudentResearchScalarFieldEnum = {
  id: 'id',
  title: 'title',
  role: 'role',
  date: 'date',
  conference: 'conference',
  publicationUrl: 'publicationUrl',
  orderId: 'orderId',
  createdAt: 'createdAt'
} as const

export type StudentResearchScalarFieldEnum = (typeof StudentResearchScalarFieldEnum)[keyof typeof StudentResearchScalarFieldEnum]


export const BusinessOrderScalarFieldEnum = {
  id: 'id',
  orderCode: 'orderCode',
  businessName: 'businessName',
  ownerName: 'ownerName',
  email: 'email',
  phone: 'phone',
  address: 'address',
  businessType: 'businessType',
  productCategories: 'productCategories',
  websiteFeatures: 'websiteFeatures',
  preferredDomain: 'preferredDomain',
  designStyle: 'designStyle',
  socialLinks: 'socialLinks',
  additionalNotes: 'additionalNotes',
  logoUpload: 'logoUpload',
  businessImages: 'businessImages',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BusinessOrderScalarFieldEnum = (typeof BusinessOrderScalarFieldEnum)[keyof typeof BusinessOrderScalarFieldEnum]


export const HeroContentScalarFieldEnum = {
  id: 'id',
  badge: 'badge',
  title: 'title',
  subtitle: 'subtitle',
  ctaText: 'ctaText',
  ctaLink: 'ctaLink',
  cta2Text: 'cta2Text',
  cta2Link: 'cta2Link',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type HeroContentScalarFieldEnum = (typeof HeroContentScalarFieldEnum)[keyof typeof HeroContentScalarFieldEnum]


export const SEOSettingsScalarFieldEnum = {
  id: 'id',
  siteName: 'siteName',
  tagline: 'tagline',
  description: 'description',
  keywords: 'keywords',
  ogImage: 'ogImage',
  twitterHandle: 'twitterHandle',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SEOSettingsScalarFieldEnum = (typeof SEOSettingsScalarFieldEnum)[keyof typeof SEOSettingsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  project?: Prisma.ProjectOmit
  service?: Prisma.ServiceOmit
  blogPost?: Prisma.BlogPostOmit
  contactMessage?: Prisma.ContactMessageOmit
  siteSetting?: Prisma.SiteSettingOmit
  testimonial?: Prisma.TestimonialOmit
  technology?: Prisma.TechnologyOmit
  studentOrder?: Prisma.StudentOrderOmit
  studentAward?: Prisma.StudentAwardOmit
  studentCertificate?: Prisma.StudentCertificateOmit
  studentResearch?: Prisma.StudentResearchOmit
  businessOrder?: Prisma.BusinessOrderOmit
  heroContent?: Prisma.HeroContentOmit
  sEOSettings?: Prisma.SEOSettingsOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

